#!/usr/bin/with-contenv /bin/bash
hasexe=$(find /home/user/coolq -maxdepth 1 -type f -name '*.exe')
if [ "$hasexe" != "" ] ; then
    echo 'CoolQ already exists, skip download.'
else
    echo 'Downloading CoolQ ...'
    mkdir /tmp/cq
    wget $COOLQ_URL -O /tmp/cq/coolq.zip
    echo 'Unzipping CoolQ ...'
    cd /tmp/cq
    LC_ALL=zh_CN.UTF-8 unzip coolq.zip > /dev/null
    mv */* /home/user/coolq
    chown -R user:user /home/user/coolq
    wget https://github.com/richardchien/coolq-http-api/releases/download/v3.3.1/io.github.richardchien.coolqhttpapi.cpk \
      -O /home/user/coolq/app/io.github.richardchien.coolqhttpapi.cpk
    rm -rf /tmp/cq
    sed "s/<QQ_id>/$COOLQ_ACCOUNT/g" /home/user/CQP.cfg > /home/user/coolq/conf/CQP.cfg
    mkdir /home/user/coolq/app/io.github.richardchien.coolqhttpapi/
    cp /home/user/app/io.github.richardchien.coolqhttpapi/config.cfg \
      /home/user/coolq/app/io.github.richardchien.coolqhttpapi/config.cfg
fi
